### ISSUE TITLE
识别率确实提高了！

### ISSUE THREAD

**Issue by liuxiaofan** [qhxin/qhQrCodeReader#1]
确实如作者所说，提高了二维码识别率，厉害！
有两个问题
1，php-qrcode-detector-decoder 这个最近更新了，我直接在你的这个里面直接更新，没事吧？
2，识别普通的二维码没问题，识别经过美化的个性二维码，也是识别失败，请问有解决方案吗？

**Comment by qhxin** [comment]
1、没问题的。detector内部没有改动。
2、不知道是什么样子的美化个性二维码呢？

**Comment by liuxiaofan** [comment]
类似第九工厂的二维码
