### ISSUE TITLE
试了几个zxing PHP无法读取的二维码，你这个都能读取

### ISSUE THREAD

**Issue by EasonJolter** [qhxin/qhQrCodeReader#3]
初步判断，你这个版本比zxing php好用

**Comment by EasonJolter** [comment]
我看了里面的代码，好像也是用zxing的方案。不过你增加了一个img_tmp文件夹，是把图片都转换成png，提高识别率？

**Comment by qhxin** [comment]
@LisenH 是尝试不同大小的图片分辨率，来看识别效果。
